"""empty message

Revision ID: 877f31d4bfa4
Revises: be5313b5dc36
Create Date: 2021-03-20 20:39:33.961827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877f31d4bfa4'
down_revision = 'be5313b5dc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'state')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'phone')
    op.drop_column('venues', 'image_link')
    op.drop_column('venues', 'genres')
    op.drop_column('venues', 'facebook_link')
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'address')
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'state')
    op.drop_column('artists', 'seeking_talent')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'phone')
    op.drop_column('artists', 'image_link')
    op.drop_column('artists', 'genres')
    op.drop_column('artists', 'facebook_link')
    op.drop_column('artists', 'city')
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###
