"""empty message

Revision ID: 966826c4a195
Revises: 570ea0d4140c
Create Date: 2021-02-23 15:22:09.163297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966826c4a195'
down_revision = '570ea0d4140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=256), nullable=True))
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('Artist', 'address')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
